# Site settings
name: Blocklee's Blog
email: block.lee121@gmail.com
author: blocklee
url: http://blocklee.github.io
resume_site: http://blocklee.github.io/
github: https://github.com/blocklee/
baseurl:
description: Actually, less is more!
meta_description: 倚栏听风;个人博客;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 山本无忧，因雪白头。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: blocklee

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

plugins:
  - jekyll-paginate