# Site settings
name: Blocklee Blog
email: block.lee121@gmail.com
author: blocklee
url: http://blocklee.github.io
resume_site: http://blocklee.github.io/
github: https://github.com/blocklee/
baseurl:
description: 生命不止,折腾不休.
meta_description: 倚栏听风;个人博客;生命不止,折腾不休.
motto: It's our wits that make us men.
banner: 水本无愁，因风起皱；山本无忧，因雪白头。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: blocklee

# Build settings
markdown: kramdown

baidu_analysis: 50b5c70ccc1e1b93f354fe4b6b5d9703

plugins:
  - jekyll-paginate